pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK17'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Run Tests') {
            steps {
                dir('selenium-pom-framework') {
            sh 'mvn clean test'
        }
        }
    }

    post {
        always {
             echo 'Build completed'
        }
    }
}
