pipeline {
    agent any
    
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/neha581/QA-Engineer-Portfolio.git'
            }
        }
        
        stage('Build') {
            steps {
                sh '/opt/homebrew/bin/mvn clean compile'
            }
        }

        stage('Run Tests') {
            steps {
                sh '/opt/homebrew/bin/mvn test'
            }
        }

        stage('Generate Reports') {
            steps {
                sh '/opt/homebrew/bin/mvn surefire-report:report'
            }
        }
    }
}
