pipeline {
    agent any
    
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/neha581/QA-Engineer-Portfolio.git'
            }
        }
        
        stage('Build') {
            steps {
                sh '/opt/homebrew/bin/mvn -f demoQA/pom.xml clean compile' 
            }
        }

        stage('Run Tests') {
            steps {
                sh '/opt/homebrew/bin/mvn -f demoQA/pom.xml test'
            }
        }

        stage('Generate Reports') {
            steps {
                sh '/opt/homebrew/bin/mvn -f demoQA/pom.xml surefire-report:report'
            }
        }
    }
}
